# Generated by Django 4.2 on 2026-04-03
# Event-Driven Automation (EDA) models: EventRule, EventLog, OutboundWebhook

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0196_add_model_indexes'),
    ]

    operations = [
        # --- EventRule ---
        migrations.CreateModel(
            name='EventRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=None, editable=False)),
                ('modified', models.DateTimeField(default=None, editable=False)),
                ('description', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(
                    default=None, editable=False, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='%(class)s_created+',
                    to='auth.user',
                )),
                ('modified_by', models.ForeignKey(
                    default=None, editable=False, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='%(class)s_modified+',
                    to='auth.user',
                )),
                ('name', models.CharField(max_length=512)),
                ('organization', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.CASCADE,
                    related_name='event_rules', to='main.organization',
                )),
                ('enabled', models.BooleanField(default=True)),
                ('source_type', models.CharField(
                    choices=[
                        ('webhook_generic', 'Generic Webhook'),
                        ('webhook_github', 'GitHub'),
                        ('webhook_gitlab', 'GitLab'),
                        ('alertmanager', 'Alertmanager'),
                        ('pagerduty', 'PagerDuty'),
                        ('datadog', 'Datadog'),
                        ('cloudwatch', 'CloudWatch'),
                    ],
                    default='webhook_generic',
                    max_length=32,
                )),
                ('webhook_path', models.SlugField(max_length=128, unique=True)),
                ('webhook_key', models.CharField(blank=True, default='', max_length=64)),
                ('conditions', models.JSONField(blank=True, default=list)),
                ('actions', models.JSONField(default=list)),
                ('throttle_seconds', models.PositiveIntegerField(default=0)),
                ('last_fired_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('fire_count', models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                'app_label': 'main',
                'ordering': ('name',),
                'unique_together': {('organization', 'name')},
            },
        ),

        # --- EventLog ---
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event_rule', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL,
                    related_name='event_logs', to='main.eventrule',
                )),
                ('event_rule_name', models.CharField(blank=True, default='', max_length=512)),
                ('source_type', models.CharField(blank=True, default='', max_length=32)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('event_type', models.CharField(blank=True, default='', max_length=128)),
                ('event_guid', models.CharField(blank=True, default='', max_length=256)),
                ('payload', models.JSONField(default=dict)),
                ('headers', models.JSONField(default=dict)),
                ('conditions_matched', models.BooleanField(default=False)),
                ('condition_results', models.JSONField(blank=True, default=list)),
                ('actions_triggered', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(
                    choices=[
                        ('received', 'Received'),
                        ('matched', 'Matched'),
                        ('unmatched', 'Unmatched'),
                        ('throttled', 'Throttled'),
                        ('action_fired', 'Action Fired'),
                        ('action_failed', 'Action Failed'),
                        ('error', 'Error'),
                        ('signature_failed', 'Signature Failed'),
                    ],
                    default='received',
                    max_length=20,
                )),
                ('error_detail', models.TextField(blank=True, default='')),
                ('job_id', models.IntegerField(blank=True, null=True)),
                ('organization', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='event_logs', to='main.organization',
                )),
            ],
            options={
                'app_label': 'main',
                'ordering': ('-created',),
            },
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['-created'], name='main_eventl_created_idx'),
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['event_rule', '-created'], name='main_eventl_rule_created_idx'),
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['status'], name='main_eventl_status_idx'),
        ),

        # --- OutboundWebhook ---
        migrations.CreateModel(
            name='OutboundWebhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=None, editable=False)),
                ('modified', models.DateTimeField(default=None, editable=False)),
                ('description', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(
                    default=None, editable=False, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='%(class)s_created+',
                    to='auth.user',
                )),
                ('modified_by', models.ForeignKey(
                    default=None, editable=False, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='%(class)s_modified+',
                    to='auth.user',
                )),
                ('name', models.CharField(max_length=512)),
                ('organization', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.CASCADE,
                    related_name='outbound_webhooks', to='main.organization',
                )),
                ('url', models.URLField(max_length=1024)),
                ('webhook_key', models.CharField(blank=True, default='', max_length=64)),
                ('events', models.JSONField(default=list)),
                ('custom_headers', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('ssl_verify', models.BooleanField(default=True)),
                ('last_status', models.CharField(
                    blank=True, choices=[('success', 'Success'), ('failed', 'Failed')],
                    default='', max_length=20,
                )),
                ('last_sent_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_error', models.TextField(blank=True, default='', editable=False)),
            ],
            options={
                'app_label': 'main',
                'ordering': ('name',),
                'unique_together': {('organization', 'name')},
            },
        ),
    ]
