# Generated by Django 4.2 on 2026-04-05
# Add survey_enabled and survey_spec fields to WorkflowJobTemplateNode

from django.db import migrations, models
import ansible_base.lib.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0198_drift_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowjobtemplatenode',
            name='survey_enabled',
            field=models.BooleanField(default=False, help_text='Whether this node has its own survey for collecting variables at launch time.'),
        ),
        migrations.AddField(
            model_name='workflowjobtemplatenode',
            name='survey_spec',
            field=models.JSONField(blank=True, default=dict, help_text='Survey specification for this node.'),
        ),
    ]
